# Generated by Django 3.1.6 on 2021-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavepool', '0002_alter_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='source',
            field=models.URLField(unique=True),
        ),
    ]
